### PR TITLE
DEVANAGARI DANDA instead of full stop in Hindi #26 

### PR DESCRIPTION
**Pull request by divanshujain**
Added another switch case for hindi keyboard. Please review and merge

### CODE REVIEW

**Comment by divanshujain** [comment]
#26

**Comment by jishnu7** [comment]
This enables Danda only for phonetic layout. Transliteration method still use full stop.

**Comment by divanshujain** [comment]
okay. Will add danda to transliteration and resend by tonight.

**Comment by divanshujain** [comment]
Realized that in the transliteration keyboard, the full stop doesn't become a danda. Where are the character transliterations defined ? Any resources or help because I don't know how that happens.

**Comment by jishnu7** [comment]
This is already fixed in https://github.com/smc/Indic-Keyboard/commit/038d52fe74d281d7dd3822aeebdd0e4b51ad6a5c

**Pull request closed without merging**
